artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # We use the dataset name for the HuggingFace loader
  dataset_name: "lex_glue"
  subset_name: "ledgar" 
  local_data_file: artifacts/data_ingestion/data.csv